-- MySQL Script generated by MySQL Workbench
-- 07/15/14 23:49:14
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mypet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mypet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mypet` ;

-- -----------------------------------------------------
-- Table `mypet`.`Tabla_Postal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Tabla_Postal` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Tabla_Postal` (
  `CODIGO` VARCHAR(100) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Cliente` (
  `DNI` VARCHAR(8) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL,
  `APELLIDO_PATERNO` VARCHAR(100) NULL,
  `APELLIDO_MATERNO` VARCHAR(100) NULL,
  `DIRECCION` VARCHAR(100) NULL,
  `CODIGO_POSTAL` VARCHAR(100) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `CODIGO_POSTAL_idx` (`CODIGO_POSTAL` ASC),
  CONSTRAINT `CODIGO_POSTAL`
    FOREIGN KEY (`CODIGO_POSTAL`)
    REFERENCES `mypet`.`Tabla_Postal` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Mascota` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Mascota` (
  `DNI` VARCHAR(8) NOT NULL,
  `ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `RAZA` VARCHAR(45) NULL,
  `ESPECIE` VARCHAR(45) NULL,
  `FECHA_NACIMIENTO` DATETIME NULL,
  PRIMARY KEY (`DNI`, `ID`),
  CONSTRAINT `ID`
    FOREIGN KEY (`DNI`)
    REFERENCES `mypet`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Producto` (
  `CODIGO` VARCHAR(20) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL,
  `STOCK_ACTUAL` INT NULL,
  `STOCK_DISPONIBLE` INT NULL,
  `PRECIO` DECIMAL(10,2) NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Boleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Boleta` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Boleta` (
  `NUMERO` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(8) NULL,
  `RAZON_SOCIAL` VARCHAR(150) NULL,
  `BRUTOS` DECIMAL(10,2) NULL,
  `DESCUENTO` DECIMAL(10,2) NULL,
  `IGV` DECIMAL(10,2) NULL,
  `VALOR_VENTA` DECIMAL(10,2) NULL,
  PRIMARY KEY (`NUMERO`),
  INDEX `DNI_idx` (`DNI` ASC),
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `mypet`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Detalle_Boleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Detalle_Boleta` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Detalle_Boleta` (
  `NUMERO` INT NOT NULL,
  `ID` INT NOT NULL,
  `CODIGO` VARCHAR(20) NULL,
  `DESCRIPCION` VARCHAR(100) NULL,
  `CANTIDAD` INT NULL,
  `BRUTO` DECIMAL(10,2) NULL,
  `DESCUENTO` DECIMAL(10,2) NULL,
  `IGV` DECIMAL(10,2) NULL,
  `VALOR_VENTA` DECIMAL(10,2) NULL,
  PRIMARY KEY (`NUMERO`, `ID`),
  INDEX `CODIGO_idx` (`CODIGO` ASC),
  CONSTRAINT `NUMERO`
    FOREIGN KEY (`NUMERO`)
    REFERENCES `mypet`.`Boleta` (`NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CODIGO`
    FOREIGN KEY (`CODIGO`)
    REFERENCES `mypet`.`Producto` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Medico` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Medico` (
  `CODIGO` VARCHAR(8) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL,
  `APELLIDO_PATERNO` VARCHAR(100) NULL,
  `APELLIDO_MATERNO` VARCHAR(100) NULL,
  `CODIGO_ESPECIALIDAD` INT NULL,
  `FECHA_NACIMIENTO` DATETIME NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Variables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Variables` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Variables` (
  `ID` INT NOT NULL,
  `RAZON_SOCIAL` VARCHAR(100) NULL,
  `UTLTIMA_BOLETA` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Historia_Clinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Historia_Clinica` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Historia_Clinica` (
  `ID_MASCOTA` INT NOT NULL,
  `ID` INT NOT NULL,
  `CITA` INT NULL,
  `RECETA` INT NULL,
  `DESCRIPCION` VARCHAR(200) NULL,
  PRIMARY KEY (`ID_MASCOTA`, `ID`),
  INDEX `ID_MASCOTA_idx` (`ID_MASCOTA` ASC),
  CONSTRAINT `ID_MASCOTA`
    FOREIGN KEY (`ID_MASCOTA`)
    REFERENCES `mypet`.`Mascota` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Cita` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Cita` (
  `ID` INT NOT NULL,
  `CODIGO_MEDICO` VARCHAR(8) NULL,
  `DNI_CLIENTE` VARCHAR(8) NULL,
  `ID_MASCOTA` INT NULL,
  `FECHA` DATETIME NULL,
  `HORA` VARCHAR(5) NULL,
  `ESTADO` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_MEDICO_idx` (`CODIGO_MEDICO` ASC),
  INDEX `ID_MASCOTA_idx` (`ID_MASCOTA` ASC),
  INDEX `DNI_CLIENTE_idx` (`DNI_CLIENTE` ASC),
  CONSTRAINT `ID_MEDICO`
    FOREIGN KEY (`CODIGO_MEDICO`)
    REFERENCES `mypet`.`Medico` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_MASCOTA`
    FOREIGN KEY (`ID_MASCOTA`)
    REFERENCES `mypet`.`Mascota` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_CLIENTE`
    FOREIGN KEY (`DNI_CLIENTE`)
    REFERENCES `mypet`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Estado` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Estado` (
  `ID` INT NOT NULL,
  `DESCRIPCION` VARCHAR(30) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Tipo_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Tipo_Usuario` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Tipo_Usuario` (
  `ID` INT NOT NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mypet`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mypet`.`Usuario` (
  `CODIGO` VARCHAR(8) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL,
  `APELLIDO_PATERNO` VARCHAR(100) NULL,
  `APELLIDO_MATERNO` VARCHAR(100) NULL,
  `CORREO` VARCHAR(100) NULL,
  `FECHA_INGRESO` DATETIME NULL,
  `ESTADO` INT NULL,
  `TIPO_USUARIOS` INT NULL,
  PRIMARY KEY (`CODIGO`),
  INDEX `ESTADO_idx` (`ESTADO` ASC),
  INDEX `TIPO_USUARIO_idx` (`TIPO_USUARIOS` ASC),
  CONSTRAINT `ESTADO`
    FOREIGN KEY (`ESTADO`)
    REFERENCES `mypet`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TIPO_USUARIO`
    FOREIGN KEY (`TIPO_USUARIOS`)
    REFERENCES `mypet`.`Tipo_Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
